### ISSUE TITLE
Add classes to show elements only in light/dark mode

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#1397]
We may consider inverting images while in dark mode. One option using CSS:

```css
img {
   -webkit-filter: invert(1);
   filter: invert(1);
}
```

Don't know if this would work better for all images, but at least it turns the ISBN image

![image](https://user-images.githubusercontent.com/5736113/66697360-32718380-ecd5-11e9-84ce-8b0e026704f4.png)

into

![image](https://user-images.githubusercontent.com/5736113/66697385-6b115d00-ecd5-11e9-8c9e-6c59a9d2046e.png)

Might even look better if I make the background of the image transparant.
