### ISSUE TITLE
Dark mode uses different background shades in feedback table

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#2337]
Dark mode:
```css
.highlighter-rouge { background: #282a36; }
.feedback-table .description { background-color: #37474f; }
```

![image](https://user-images.githubusercontent.com/5736113/95897954-9c13ea00-0d8e-11eb-86d9-2c6409b055aa.png)

White mode:
```css
.feedback-table .description { background: #eeeeee; }
```

![image](https://user-images.githubusercontent.com/5736113/95897988-aafa9c80-0d8e-11eb-8c42-491181de14f2.png)
