### ISSUE TITLE
Update browserlist

### ISSUE THREAD

**Issue by bmesuere** [dodona-edu/dodona#2733]
Right now, we seem to have 2 browserlist files: .browserlistrc and browserlist. I think these files are used for both webpack and the autoprefixer for css, but I don't know which file is use for which tool.

The contents of both files is:
```
Last 3 versions
Firefox ESR
```

autoprefixer outputs this as list of browsers we support:
```
  Chrome for Android: 87
  Firefox for Android: 83
  QQ Browser: 10.4
  UC for Android: 12.12
  Android: 81
  Baidu Browser: 7.12
  Bb: 10, 7
  Chrome: 87, 86, 85
  Edge: 87, 86, 85
  Firefox: 84, 83, 82, 78
  IE: 11, 10, 9
  IE Mobile: 11, 10
  iOS Safari: 14.0-14.3, 13.4-13.7, 13.3
  KaiOS Browser: 2.5
  Opera Mini: all
  Opera Mobile: 59, 12.1, 12
  Opera: 72, 71, 70
  Safari: 14, 13.1, 13
  Samsung Internet: 13.0, 12.0, 11.1-11.2

These browsers account for 91.94% of all users globally
```
<details>
 <summary>With this list of prefixes</summary>

````
At-Rules:
  @keyframes: webkit
  @resolution: webkit, o
  @viewport: ms, o

Selectors:
  ::backdrop: webkit
  ::placeholder: webkit, moz, -ms- old, ms
  ::selection: moz
  :any-link: webkit, moz
  :fullscreen: webkit, ms
  :placeholder-shown: moz, ms
  :read-only: moz
  :read-write: moz

Properties:
  align-content: -webkit- 2009, ms
  align-items: -webkit- 2009, ms
  align-self: -webkit- 2009, ms
  animation-delay: webkit
  animation-direction: webkit
  animation-duration: webkit
  animation-fill-mode: webkit
  animation-iteration-count: webkit
  animation-name: webkit
  animation-play-state: webkit
  animation-timing-function: webkit
  animation: webkit
  appearance: webkit, moz
  backdrop-filter: webkit
  backface-visibility: webkit
  background-clip: webkit
  border-block-end: webkit
  border-block-start: webkit
  border-image: o
  border-inline-end: webkit
  border-inline-start: webkit
  box-decoration-break: webkit
  box-shadow: webkit
  box-sizing: webkit
  break-after: webkit, moz
  break-before: webkit, moz
  break-inside: webkit, moz
  clip-path: webkit
  color-adjust: webkit
  column-count: webkit, moz
  column-fill: webkit, moz
  column-gap: webkit, moz
  column-rule-color: webkit, moz
  column-rule-style: webkit, moz
  column-rule-width: webkit, moz
  column-rule: webkit, moz
  column-span: webkit, moz
  column-width: webkit, moz
  columns: webkit, moz
  filter: webkit
  flex-basis: -webkit- 2009, ms
  flex-direction: -webkit- 2009, ms
  flex-flow: -webkit- 2009, ms
  flex-grow: -webkit- 2009, ms
  flex-shrink: -webkit- 2009, ms
  flex-wrap: -webkit- 2009, ms
  flex: -webkit- 2009, ms
  flow-from: ms
  flow-into: ms
  font-feature-settings: webkit
  font-kerning: webkit
  font-language-override: webkit
  font-variant-ligatures: webkit
  grid-area *: ms
  grid-column *: ms
  grid-column-align *: ms
  grid-column-end *: ms
  grid-column-start *: ms
  grid-row *: ms
  grid-row-align *: ms
  grid-row-end *: ms
  grid-row-start *: ms
  grid-template *: ms
  grid-template-areas *: ms
  grid-template-columns *: ms
  grid-template-rows *: ms
  hyphens: webkit, ms
  image-rendering: ms
  justify-content: -webkit- 2009, ms
  margin-block-end: webkit
  margin-block-start: webkit
  margin-inline-end: webkit
  margin-inline-start: webkit
  mask-border-outset: webkit
  mask-border-repeat: webkit
  mask-border-slice: webkit
  mask-border-source: webkit
  mask-border-width: webkit
  mask-border: webkit
  mask-clip: webkit
  mask-composite: webkit
  mask-image: webkit
  mask-origin: webkit
  mask-position: webkit
  mask-repeat: webkit
  mask-size: webkit
  mask: webkit
  object-fit: o
  object-position: o
  order: -webkit- 2009, ms
  overscroll-behavior: ms
  padding-block-end: webkit
  padding-block-start: webkit
  padding-inline-end: webkit
  padding-inline-start: webkit
  perspective-origin: webkit
  perspective: webkit
  place-self: ms
  region-fragment: ms
  scroll-snap-coordinate: ms
  scroll-snap-destination: ms
  scroll-snap-points-x: ms
  scroll-snap-points-y: ms
  scroll-snap-type: ms
  tab-size: moz, o
  text-align-last: moz
  text-decoration-color: webkit
  text-decoration-line: webkit
  text-decoration-skip-ink: webkit
  text-decoration-skip: webkit
  text-decoration-style: webkit
  text-decoration: webkit
  text-emphasis-color: webkit
  text-emphasis-position: webkit
  text-emphasis-style: webkit
  text-emphasis: webkit
  text-orientation: webkit
  text-overflow: o
  text-size-adjust: webkit, moz, ms
  text-spacing: ms
  touch-action: ms
  transform-origin: webkit, ms
  transform-style: webkit
  transform: webkit, ms
  transition-delay: webkit, o
  transition-duration: webkit, o
  transition-property: webkit, o
  transition-timing-function: webkit, o
  transition: webkit, o
  user-select: webkit, moz, ms
  writing-mode: webkit, ms

Values:
  cross-fade: webkit
  element: moz
  fill-available: webkit, moz
  fill: webkit, moz
  fit-content: webkit, moz
  flex: -webkit- 2009, ms
  grab: webkit
  grabbing: webkit
  grid *: ms
  image-set: webkit
  inline-flex: -webkit- 2009, ms
  inline-grid *: ms
  isolate-override: moz
  isolate: webkit, moz
  linear-gradient: -webkit- old, o
  max-content: webkit, moz
  min-content: webkit, moz
  pixelated: webkit, moz, o
  plaintext: moz
  radial-gradient: -webkit- old, o
  repeating-linear-gradient: -webkit- old, o
  repeating-radial-gradient: -webkit- old, o
  stretch: webkit, moz
  zoom-in: webkit
  zoom-out: webkit

* - Prefixes will be added only on grid: true option.
````

</details>

Bootstrap has a different list of supported browsers, so it would make sense to change our css browserlist to the one they use:
```
>= 0.5%
last 2 major versions # bootstrap uses 2, I propose 3 here
not dead
Chrome >= 60
Firefox >= 60
Firefox ESR
iOS >= 12
Safari >= 12
not Explorer <= 11
```

Which supports these browsers:
```
  Chrome for Android: 87
  Firefox for Android: 83
  QQ Browser: 10.4
  UC for Android: 12.12
  Android: 81
  Baidu Browser: 7.12
  Chrome: 87, 86, 85, 84, 83, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66, 65, 64, 63, 62, 61, 60
  Edge: 87, 86, 85
  Firefox: 84, 83, 82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66, 65, 64, 63, 62, 61, 60
  iOS Safari: 14.0-14.3, 13.4-13.7, 13.3, 13.2, 13.0-13.1, 12.2-12.4, 12.0-12.1
  KaiOS Browser: 2.5
  Opera Mini: all
  Opera Mobile: 59
  Opera: 72, 71, 70
  Safari: 14, 13.1, 13, 12.1, 12
  Samsung Internet: 13.0, 12.0, 11.1-11.2

These browsers account for 94.03% of all users globally
```

<details>
 <summary>With this list of prefixes</summary>

```
At-Rules:
  @keyframes: webkit
  @resolution: webkit
  @viewport: o

Selectors:
  ::backdrop: webkit
  ::placeholder: moz
  ::selection: moz
  :any-link: webkit, moz
  :fullscreen: webkit, moz
  :placeholder-shown: moz
  :read-only: moz
  :read-write: moz

Properties:
  animation-delay: webkit
  animation-direction: webkit
  animation-duration: webkit
  animation-fill-mode: webkit
  animation-iteration-count: webkit
  animation-name: webkit
  animation-play-state: webkit
  animation-timing-function: webkit
  animation: webkit
  appearance: webkit, moz
  backdrop-filter: webkit
  backface-visibility: webkit
  background-clip: webkit
  border-block-end: webkit
  border-block-start: webkit
  border-image: o
  border-inline-end: webkit
  border-inline-start: webkit
  box-decoration-break: webkit
  break-after: moz
  break-before: moz
  break-inside: moz
  clip-path: webkit
  color-adjust: webkit
  column-count: moz
  column-fill: moz
  column-gap: moz
  column-rule-color: moz
  column-rule-style: moz
  column-rule-width: moz
  column-rule: moz
  column-span: moz
  column-width: moz
  columns: moz
  font-kerning: webkit
  hyphens: webkit
  margin-block-end: webkit
  margin-block-start: webkit
  margin-inline-end: webkit
  margin-inline-start: webkit
  mask-border-outset: webkit
  mask-border-repeat: webkit
  mask-border-slice: webkit
  mask-border-source: webkit
  mask-border-width: webkit
  mask-border: webkit
  mask-clip: webkit
  mask-composite: webkit
  mask-image: webkit
  mask-origin: webkit
  mask-position: webkit
  mask-repeat: webkit
  mask-size: webkit
  mask: webkit
  object-fit: o
  object-position: o
  padding-block-end: webkit
  padding-block-start: webkit
  padding-inline-end: webkit
  padding-inline-start: webkit
  tab-size: moz, o
  text-align-last: moz
  text-decoration-color: webkit
  text-decoration-line: webkit
  text-decoration-skip-ink: webkit
  text-decoration-skip: webkit
  text-decoration-style: webkit
  text-decoration: webkit
  text-emphasis-color: webkit
  text-emphasis-position: webkit
  text-emphasis-style: webkit
  text-emphasis: webkit
  text-orientation: webkit
  text-size-adjust: webkit, moz
  user-select: webkit, moz

Values:
  cross-fade: webkit
  element: moz
  fill-available: webkit, moz
  fill: webkit, moz
  fit-content: webkit, moz
  grab: webkit
  grabbing: webkit
  image-set: webkit
  isolate-override: moz
  isolate: webkit, moz
  max-content: webkit, moz
  min-content: webkit, moz
  pixelated: moz
  plaintext: moz
  sticky: webkit
  stretch: webkit, moz
```

Changing `browserlist` had no effect, `.browserlistrc` did. This might also affect jss transpilation, I will follow up in a comment.
