### ISSUE TITLE
Tailwind css manipulates default styles on exercise pages

### ISSUE THREAD

**Issue by jorg-vr** [dodona-edu/dodona#3638]
In light mode, on an exercise detail page, links are displayed black:
![image](https://user-images.githubusercontent.com/21177904/169478372-8e545802-b840-4b20-b95e-a5e1dcaf0da7.png)

while they should be orange:
![image](https://user-images.githubusercontent.com/21177904/169478547-87c48c23-44db-48a8-aefb-00af7c25cc45.png)

This was caused by inline css from tailwind: 
```css
/*  !tailwindcss v3.0.24 | MIT License | https://tailwindcss.com */
...
/* Reset links to optimize for opt-in styling instead of opt-out. */
a {
  color: inherit;
  text-decoration: inherit;
}
```

I have not found where and why we import tailwind. 
The link colors are correct on the submission detail page.
