### ISSUE TITLE
Error when sending error mail

### ISSUE THREAD

**Issue by bmesuere** [dodona-edu/dodona#3979]
Sending some error mails fail according to the logs:

```
--- !ruby/object:ActiveJob::QueueAdapters::DelayedJobAdapter::JobWrapper
job_data:
  job_class: ActionMailer::MailDeliveryJob
  job_id: 3a586ccc-98a6-4807-8325-c4ca9ee380f3
  provider_job_id: 
  queue_name: default
  priority: 
  arguments:
  - ApplicationMailer
  - user_unable_to_log_in
  - deliver_now
  - params:
      authinfo: 
      errors: '#<ActiveModel::Errors [#<ActiveModel::Error attribute=email, type=taken,
        options={:allow_blank=>true, :value=>"xxxxxxxxxxxx"}>]>'
      _aj_symbol_keys:
      - authinfo
      - errors
    args: []
    _aj_ruby2_keywords:
    - params
    - args
  executions: 0
  exception_executions: {}
  locale: nl
  timezone: Brussels
  enqueued_at: '2022-09-05T13:51:57Z'
Last Error
Toggle full message
undefined method `[]' for nil:NilClass

    uid = authinfo['uid']
                  ^^^^^^^
/home/dodona/rails/releases/20220901125306/app/mailers/application_mailer.rb:37:in `user_unable_to_log_in'
```
